server: 
  port: 9090

spring: 
  datasource: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
    
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
      
  servlet: 
    multipart: 
      max-file-size: 10MB