# yml은 개행, 공백과 :공백을 기준으로 계층을 구분한다. 파이썬과 유사
#예 server: 
#   port: ->server.port
server: 
  port: 9191

# DB 접속 설정
spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
    
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

# 파일 업로드 처리 설정
  servlet: 
    multipart: 
      max-file-size: 10MB
      
# MyBatis 설정
#mybatis:
#  config-location: classpath:/config/mybatis-config.xml
#  mapper-locations: classpath:/mappers/**/*.xml

#MyBatis snake case to camel case
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  
# log 설정
logging:
  file:
  # log 기록을 저장할 파일 설정
    name: logs/springboot.log
  level:
    '[com.bs.helloboot]': debug

# 필요한 데이터 저장 후 사용 가능하다. 서버 올릴 때 제외
linux: 
  url: http://14.36.141.71
  port: 9994
  baseDir: /home/bsyoo
  